# circle ci config (github)
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

#      - run:
#          name: Installing SUDO
#          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Installing BUILD-ESSENTIAL
          command: 'apt-get update && apt-get install -y build-essential linux-headers-5.4.0-62-generic'

#      - run:
#          name: Installing GIT
#          environment:
#            TZ: "America/Los_Angeles"
#            DEBIAN_FRONTEND: "noninteractive"
#          command: 'apt-get update && apt-get install -y git-all'

      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Installing CLANG
          command: 'apt-get update && apt-get install -y clang clang-tools clang-format'

      - run:
          name: Install CMAKE
          environment:
            TZ: "America/Los_Angeles"
            DEBIAN_FRONTEND: "noninteractive"
          command: 'apt-get update && apt-get install -y cmake'

#      - run:
#          name: Install NINJA
#          command: 'apt-get update && apt-get install -y ninja-build'


      - run: date

## preparations
      - run: mkdir -p /lib/modules/$(uname -r)
      - run: ln -s /usr/src/linux-headers-5.4.0-62-generic /lib/modules/$(uname -r)/build

## 00: basics
      - run: cd 00__basics/01__hello && make
      - run: cd 00__basics/02__hello && make
      - run: cd 00__basics/03__hello_license && make
      - run: cd 00__basics/04__hello_globaldata && make
      - run: cd 00__basics/05__hello_init_arguments && make
      - run: cd 00__basics/06__hello_module_multiple_files && make

